services:
  device:
    image: chandankatterishashikumar/dockerautomation-pipeline:${IMAGE_TAG}
    build:
      context: ./Device/.
  
  automation:
    image: chandankatterishashikumar/dockerautomation-pipeline:${IMAGE_TAG}
    build:
      context: ./Automation/.
    depends_on: 
      - device
    volumes:
      - ./automation_reports:/automation/reports/
