services:
  device:
    image: dockerautomation-pipeline-device:${IMAGE_TAG}
    build:
      context: ./Device/.
  
  automation:
    image: dockerautomation-pipeline-automation:${IMAGE_TAG}
    build:
      context: ./Automation/.
    depends_on: 
      - device
    volumes:
      - ./automation_reports:/automation/reports/
